repos:
    environment_template:
        actions: [git_status, git_branch]
        dir: /home/ros2_ws/src/environment_template
    ply_publisher:
        actions: [git_status, git_branch]
        dir: /home/ros2_ws/src/environment_template

actions:
    git_status:
        hz: 0.1 #5m
    git_branch:
        hz: 0.2 #5m

publish:
    mqtt:
        broker_ip: mqtt.lcas.group
        broker_port: 8883
        namespace: /mrs_fleet_dashboard
        topic: /{robot_name}/{repo}/{action}
