# MRS Fleet Dashboard Topics
workspace_dashboard:
    robot_ws:  # Robot WS
        actions: [git_status, git_branch]
        dir: /home/agilex/limo_platform
    research_ws:  # Research WS
        actions: [git_status, git_branch, git_remote]
        dir: /home/agilex/limo_ros2
    meta:
        actions: [robot_name, battery, last_online]


# Secondary Publishers
repositories:
    fleet_status_dashboard:
        actions: [git_status, git_branch]
        dir: /home/agilex/fleet_status_dashboard

actions:
    git_status:
        hz: 0.1 #5m
    git_branch:
        hz: 0.2 #5m
    git_remote:
        hz: 0.2 #5m
    robot_name:
        hz: 0.2 #5m
    battery:
        hz: 0.2 #5m
    last_online:
        hz: 0.2 #5m

publish:
    mqtt:
        broker_ip: my.broker.online
        broker_port: 1883
        namespace: mrs_fleet_dashboard
        topic: /{manufacturer}/{serial_number}/{repo}/{action}

